flask_todo/views.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_user, login_required, logout_user, current_user
from flask_todo.models import User, Task
from datetime import datetime, date
from flask_todo import db
import re

bp = Blueprint('todo_app', __name__, url_prefix='')


# 初期画面はhome.htmlを表示させます
@bp.route('/')
def home():
    return render_template('home.html')


# ログアウトするとhome.htmlに戻る
@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('todo_app.home'))


# ログイン
@bp.route('/login', methods=['GET', 'POST'])
def login():
    # 書き込まれた項目を取得する
    email = request.form.get('email')
    password = request.form.get('password')
    # POSTリクエストの場合
    if request.method == 'POST':
        user = User.select_by_email(email)
        # メールアドレスとパスワードが正しい場合
        if user and user.validate_password(password):
            login_user(user)
            next = request.args.get('next')
            if not next:
                next = url_for('todo_app.user')
            return redirect(next)
    return render_template('login.html', last_access=datetime.now())


# ユーザー登録
@bp.route('/register', methods=['GET', 'POST'])
def register():
    # 書き込まれた項目を取得する
    username = request.form.get('name')
    email = request.form.get('email')
    password1 = request.form.get('password1')
    password2 = request.form.get('password2')
    
    # メールアドレスの形式を正規表現で想定している
    pattern = "^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$"
    
    # POSTリクエストの場合
    if request.method == 'POST':
        # どこかに空欄がある場合
        if username == '' or email =='' or password1 == '' or password2 == '':
            flash('空のフォームがあります')
        # パスワードが一致しない場合
        elif password1 != password2:
            flash('パスワードが一致しません')
        # メールアドレスの形式になっていない場合
        elif re.match(pattern, email) is None:
            flash('メールアドレスの形式になっていません')
        # 全て正しく入力された場合
        else:
            # 書き込まれた項目を取得する
            user = User(
                email = email,
                username = username,
                password = password1
                )
            # データベースにあるメールアドレスを取得する
            # データベースにメールアドレスが登録されていなければNoneとなる
            DBuser = User.select_by_email(email)
            
            # メールアドレスが取得された場合
            if DBuser != None:
                flash('登録済みです')
            # メールアドレスが取得されなかった場合
            else:
                # データベースへの書き込みを行う
                try:
                    # データベースとの接続を開始する
                    with db.session.begin(subtransactions=True):
                        # データベースに書き込むデータを用意する
                        db.session.add(user)
                    # データベースへの書き込みを実行する
                    db.session.commit()
                # 書き込みがうまくいかない場合
                except:
                    # データベースへの書き込みを行わずにロールバックする
                    db.session.rollback()
                    raise
                # データベースとの接続を終了する
                finally:
                    db.session.close()
                    
                # 成功すればlogin.htmlに遷移する
                return redirect(url_for('todo_app.login'))
    return render_template('register.html')


# タスク一覧
@bp.route('/user', methods=['GET', 'POST'])
# ログインできている時に処理を実行できる
@login_required
def user():
    # GETリクエストの場合
    if request.method == 'GET':
        # 現在ログインしている人のタスクをタスク終了日が早い順に全て取得する
        tasks = Task.query.filter(Task.user_id == current_user.get_id()).order_by(Task.end_time).all()
    return render_template('user.html',tasks=tasks, today=date.today())
    
        
# 新規タスク作成
@bp.route('/create_task', methods=['GET', 'POST'])
# ログインできている時に処理を実行できる
@login_required
def create_task():
    # POSTリクエストの場合
    if request.method == 'POST':        
        # 書き込まれた項目を取得する
        title = request.form.get('title')
        detail = request.form.get('detail')
        end_time = datetime.strptime(request.form.get('end_time'), '%Y-%m-%d')
        
        # どこかに空欄がある場合
        if title == '' or detail =='' or end_time == '':
            flash('空のフォームがあります')
		# 全て正しく入力された場合
        else:
            # 取得した項目をデータベースのカラム名に紐付ける
            create_task = Task(
                title = title,
                end_time = end_time,
                detail = detail,
                user_id = current_user.get_id()
                )
            
            # データベースへの書き込み（Create処理）
            try:
                with db.session.begin(subtransactions=True):
                    db.session.add(create_task)
                db.session.commit()
            except:
                db.session.rollback()
                raise
            finally:
                db.session.close()
                
            return redirect(url_for('todo_app.user'))
    return render_template('create_task.html')


# タスク詳細
@bp.route('/detail/<int:id>')
# ログインできている時に処理を実行できる
@login_required
def detail_task(id):
    # 選択したタスクの情報を取得（Read処理）
    task = Task.query.get(id)
    return render_template('detail.html', task=task, today=date.today())


# タスク削除
@bp.route('/delete/<int:id>')
# ログインできている時に処理を実行できる
@login_required
def delete_task(id):
    # 選択したタスクの情報を取得
    task = Task.query.get(id)
    
    # データベースへの書き込み（Delete処理）
    try:
        with db.session.begin(subtransactions=True):
            db.session.delete(task)
        db.session.commit()
    except:
        db.session.rollback()
        raise
    finally:
        db.session.close()
        
    return redirect(url_for('todo_app.user'))


# タスク更新
@bp.route('/update/<int:id>', methods=['GET', 'POST'])
# ログインできている時に処理を実行できる
@login_required
def update_task(id):
    # 選択したタスクの情報を取得
    task = Task.query.get(id)
    
    # GETリクエストの場合
    if request.method == 'GET':
        return render_template('update.html', task=task, today=date.today())
    # POSTリクエストの場合
    else:
        task.title = request.form.get('title')
        task.end_time = datetime.strptime(request.form.get('end_time'), '%Y-%m-%d')
        task.detail = request.form.get('detail')
        
        update_task = Task(
            title = task.title,
            end_time = task.end_time,
            detail = task.detail
            )
        
        # データベースへの書き込み（Update処理）
        try:
            db.session.commit()
        except:
            db.session.rollback()
            raise
        finally:
            db.session.close()
        
        return redirect(url_for('todo_app.user'))
    

flask_todo/templates/_formhelpers.html
{% macro render_field(field) %}
<dt>{{ field.label }}
    <dd>{{ field(**kwargs)| safe }}
        {% if field.errors %}
        <ul class="errors">
            {% for error in field.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </dd>
</dt>
{% endmacro %}

flask_todo/templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    
    {% block head %}
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=BIZ+UDPGothic&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{{url_for('static',filename='css/reset.css')}}">
        <link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
        {% endblock head %}
        
</head>
<body>
    <div class="wrapper">
        <div id="header">
            <ul id="nav">
                <li><a class="nav-links" href="{{url_for('todo_app.home')}}">ホーム</a></li>
                {% if current_user.is_authenticated %}
                <li><a class="nav-links" aria-current="page" href="{{ url_for('todo_app.logout') }}">ログアウト</a></li>
                {% endif %}
                <li><a class="nav-links" href="{{ url_for('todo_app.user') }}">ユーザー画面</a></li>
            </ul>
        </div>
        {% block content %}
        {% endblock content %}
    </div>
    </body>
</html>

flask_todo/templates/create_task.html
{% from "_formhelpers.html" import render_field %}
{% extends 'base.html' %}

{% block title %}タスク入力画面{% endblock %}


{% block content %}
<main>
    <form method="POST">
        <div>
            <input type="text" placeholder="タスクのタイトル" name="title">
        </div>
        <div>
            <textarea name="detail" placeholder="タスクの詳細" rows="5"></textarea>
        </div>
        <div>
            <label for="due">終了予定日</label>
            <input type="date" name="end_time" required>
        </div>
        <div>
            <button type="submit">作成</button>
            <button><a href="/user" role="button">戻る</a></button>
        </div>
    </form>
</main>
{% endblock content %}
    

flask_todo/templates/detail.html
{% from "_formhelpers.html" import render_field %}
{% extends 'base.html' %}

{% block title %}タスク詳細画面{% endblock %}

{% block content %}
<main>
    <div>
        <h2>
            {{ task.title }}
        </h2>
        <p>
            {{ task.detail }}
        </p>
        <div>
            <p>
                期限：{{ task.end_time.date() }}
            </p>
            {% if task.end_time.date() < today %}
            <button>
                期限切れです！
            </button>
            {% endif %}
        </div>
        <div>
            <button>
                <a href="/user">戻る</a>
            </button>
        </div>
    </div>
</main>
{% endblock content %}

flask_todo/templates/home.html
{% from "_formhelpers.html" import render_field %}
{% extends 'base.html' %}

{% block title %}ホーム画面{% endblock %}

{% block content %}
<main>
    <div>
        <!-- ログインが成功している場合 -->
        {% if current_user.is_authenticated %}
        <h2>
            ようこそ！{{ current_user.username }}さん
        </h2>
        <!-- ログインしていない場合 -->
        {% else %}
        <h2>
            ログイン or ユーザー登録をして下さい
        </h2>
        <form>
            <button>
                <a href="{{ url_for('todo_app.login') }}">ログイン</a>
            </button>
            <button>
                <a href="{{ url_for('todo_app.register') }}">登録</a>
            </button>
        </form>
        {% endif %}
    </div>
</main>
{% endblock content %}

flask_todo/templates/login.html
{% from "_formhelpers.html" import render_field %}
{% extends 'base.html' %}

{% block title %}ログイン画面{% endblock %}

{% block content %}
<main>
    <h2>ログインして下さい</h2>
    <form method="POST">
        <input type="text" placeholder="Email" name="email">
        <input type="password" placeholder="Password" name="password">
        <div>
            <button>ログイン</button>
        </div>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class="flashes">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
        {% endwith %}
    </form>
</main>    
{% endblock content %}

flask_todo/templates/register.html
{% from "_formhelpers.html" import render_field %}
{% extends 'base.html' %}

{% block title %}ユーザー情報登録画面{% endblock %}

{% block content %}
<main>
    <h2>登録して下さい</h2>
    <form method="post">
        <input type="text" placeholder="Name" name="name">
        <input type="text" placeholder="Email" name="email">
        <input type="password" placeholder="Password" name="password1">
        <input type="password" placeholder="Password Confirmation" name="password2">
        <div>
            <button>登録</button>
        </div>
        {% with messages = get_flashed_messages() %}
          {% if messages %}
            <ul class="flashes">
              {% for message in messages %}
              <li>{{ message }}</li>
              {% endfor %}
            </ul>
          {% endif %}
        {% endwith %}
    </form>
</main>
{% endblock content %}

flask_todo/templates/update.html
{% from "_formhelpers.html" import render_field %}
{% extends 'base.html' %}

{% block title %}タスク更新画面{% endblock %}

{% block content %}
<main>
    {% if task.end_time.date() < today %}
        <div class="">
            期限切れです！
        </div>
    {% endif %}
    <form action="/update/{{ task.id }}" method="POST">
        <div>
            <label for="title">タイトル</label>
            <input type="text" name="title" value={{ task.title }}>
        </div>
        <div>
            <label for="detail">詳細</label>
            <textarea name="detail" rows="5">{{ task.detail }}</textarea>
        </div>
        <div>
            <label for="due">日付</label>
            <input type="date" name="end_time" value={{ task.end_time.date() }} required>
        </div>
        <div>
            <button type="submit">更新</button>
            <button><a href="/user" role="button">戻る</a></button>
        </div>
    </form>
</main>
{% endblock content %}

flask_todo/templates/user.html
{% from "_formhelpers.html" import render_field %}
{% extends 'base.html' %}

{% block title %}タスク一覧画面{% endblock %}

{% block content %}
<main>
    <div>
        <div>
            <button>
                <a href="/create_task" role="button">新規作成</a>
            </button>
        </div>
        <div>
            {% for task in tasks %}
            <div>
                <div>
                    <h2>{{ task.title }}</h2>
                    <p>期限：{{ task.end_time.date() }}</p>
                    {% if task.end_time.date() < today %}
                    <button>
                        期限切れです！
                    </button>
                    {% endif %}
                    
                </div>
                <div>
                    <button><a href="/detail/{{ task.id }}" role="button">詳細</a></button>
                    <button><a href="/update/{{ task.id }}" role="button">編集</a></button>
                    <button><a href="/delete/{{ task.id }}" role="button">完了</a></button>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</main>
{% endblock content %}