login/models.py
from login import db, login_manager
from flask_bcrypt import generate_password_hash, check_password_hash
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(UserMixin, db.Model):
    
    __tablename__ = 'users'
    
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), index=True)
    password = db.Column(db.String(128))
    
    
    def __init__(self, email, username, password):
        self.email = email
        self.username = username
        self.password = generate_password_hash(password)
        
    def validate_password(self, password):
        return check_password_hash(self.password, password)
    
    def add_user(self):
        with db.session.begin(subtransactions=True):
            db.session.add(self)
        db.session.commit()
    
    @classmethod
    def select_by_email(cls, email):
        return cls.query.filter_by(email=email).first()

login/forms.py
from wtforms.form import Form
from wtforms.fields import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError
from login.models import User


class LoginForm(Form):
    email = StringField('メール: ', validators=[DataRequired(), Email()])
    password = PasswordField('パスワード: ', validators=[DataRequired()])
    submit = SubmitField('ログイン')


class RegisterForm(Form):
    email = StringField('メール： ', validators=[DataRequired(), Email()])
    username = StringField('名前： ', validators=[DataRequired()])
    password = PasswordField(
        'パスワード： ', validators=[DataRequired(), EqualTo('password_confirm', message='パスワードが一致しません')]
    )
    password_confirm = PasswordField('パスワード確認', validators=[DataRequired()])
    submit = SubmitField('登録')
    
    def validate_email(self, field):
        if User.select_by_email(field.data):
            raise ValidationError('メールアドレスは既に登録されています')
        

login/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

login_manager = LoginManager()
login_manager.login_view = 'login.login'
login_manager.login_message = 'ログインして下さい'

db = SQLAlchemy()
migrate = Migrate()

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'mysite'
    app.config['SQLALCHEMY_DATABASE_URI'] = \
      'mysql://{user}:{password}@{host}/{db_name}?charset=utf8'.format(**{
      'user': "todo_user",
      'password': "MySQL_DB_Pass",
      'host': "localhost",
      'db_name': "ToDo_DB"
      })
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    from login.views import login_bp
    app.register_blueprint(login_bp)
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)
    return app

login/views.py
from flask import Blueprint, request, render_template, redirect, url_for
from flask_login import login_user, login_required, logout_user
from login.forms import LoginForm, RegisterForm
from login.models import User


login_bp = Blueprint('login', __name__, url_prefix='')


@login_bp.route('/')
def home():
    return render_template('home.html')

@login_bp.route('/welcome')
@login_required
def welcome():
    username = User.username
    return render_template('welcome.html', username=username)

@login_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('login.home'))

@login_bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User.select_by_email(form.email.data)
        if user and user.validate_password(form.password.data):
            login_user(user)
            next = request.args.get('next')
            if not next:
                next = url_for('login.welcome')
            return redirect(next)
    return render_template('login.html', form=form)

@login_bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User(
            email = form.email.data,
            username = form.username.data,
            password = form.password.data
        )
        user.add_user()
        return redirect(url_for('login.login'))
    return render_template('register.html', form=form)

@login_bp.route('/user')
@login_required
def user():
    return render_template('user.html')

login/templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{url_for('login.home')}}">ホーム</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse show" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                    <a class="nav-link active" aria-current="page" href="{{ url_for('login.logout') }}">ログアウト</a>
                    {% else %}
                    <a class="nav-link" href="{{ url_for('login.login') }}">ログイン</a>
                    <a class="nav-link" href="{{ url_for('login.register') }}">登録</a>
                    {% endif %}
                    <a class="nav-link" href="{{ url_for('login.user') }}">ユーザー画面</a>
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
                </div>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>